### ISSUE TITLE
0.1.33: Subzero temperatures broken on DHT22

### ISSUE THREAD

**Issue by jeskata** [RobTillaart/DHTlib#11]
Using the example dht22_test on Arduino Uno and Arduino 1.8.15, I get this when I hang the sensor out the window:

DHT22, 	OK,	57.7,	0.5,	4836
DHT22, 	OK,	57.9,	0.4,	4888
DHT22, 	OK,	58.1,	0.4,	4932
DHT22, 	OK,	58.3,	0.3,	4980
DHT22, 	OK,	58.6,	0.3,	5024
DHT22, 	OK,	58.7,	0.2,	5024
DHT22, 	OK,	59.0,	0.2,	4932
DHT22, 	OK,	59.2,	0.1,	4888
DHT22, 	OK,	59.4,	0.1,	4932

TOT	OK	CRC	TO	CON	ACK_L	ACK_H	UNK
140	140	0	0	0	0	0	0

DHT22, 	OK,	59.5,	0.0,	4928
DHT22, 	OK,	59.8,	0.0,	4876
DHT22, 	OK,	60.0,	-3276.7,	5072
DHT22, 	OK,	60.2,	-3276.7,	5120
DHT22, 	OK,	60.3,	-3276.6,	5212
DHT22, 	OK,	60.6,	-3276.6,	5072
DHT22, 	OK,	60.9,	-3276.6,	5024
DHT22, 	OK,	61.1,	-3276.5,	5072
DHT22, 	OK,	61.3,	-3276.5,	5116
DHT22, 	OK,	61.4,	-3276.4,	5072
DHT22, 	OK,	61.7,	-3276.4,	5172
DHT22, 	OK,	62.0,	-3276.4,	5072
DHT22, 	OK,	62.2,	-3276.3,	5212
DHT22, 	OK,	62.3,	-3276.2,	5304
DHT22, 	OK,	62.6,	-3276.2,	5176
DHT22, 	OK,	62.8,	-3276.2,	5172
DHT22, 	OK,	63.0,	-3276.1,	5352
DHT22, 	OK,	63.2,	-3276.1,	4976
DHT22, 	OK,	63.5,	-3276.1,	5076
DHT22, 	OK,	63.7,	-3276.1,	5116

**Comment by RobTillaart** [comment]
Hi @jeskata 
Thanks for posting this issue.
Please use the [DHTNew ](https://github.com/RobTillaart/DHTNew) library if possible as it has many fixes.
It has also a fix for his subzero one.

If you definitely need this AVR-optimized version let me know, then I will fix it asap.
Rob

**Comment by RobTillaart** [comment]
@jeskata 

I have made a branch - https://github.com/RobTillaart/DHTlib/tree/develop
Can you test it?
Thanks,

**Comment by jeskata** [comment]
Yes, it seems to fix the issue.

**Comment by RobTillaart** [comment]
Then I will merge it into master,

thank you for testing!

**Comment by RobTillaart** [comment]
Released 0.1.34 

If there are no more questions you may close the issue.
