### ISSUE TITLE
esp8266 support

### ISSUE THREAD

**Issue by netpipe** [RobTillaart/DHTlib#3]
its the only library compatible with the PCF8574 far as i know.. would be super handy to add support to esp8266 for this.

https://i.imgur.com/Fw1aiuB.jpg
https://i.imgur.com/nrlvQh1.jpg

https://github.com/netpipe/Arduino-Thermostat working version

https://netpipe.ca/wp-content/uploads/2021/01/IMG_4114.resized-300x200.jpg
https://netpipe.ca/wp-content/uploads/2021/01/IMG_4117.resized-300x200.jpg

**Comment by netpipe** [comment]
In file included from /home/netpipe/Arduino/libraries/DHTLib/dht.h:18:0,
                 from /home/netpipe/Arduino/libraries/DHTLib/dht.cpp:30:
/home/netpipe/Arduino/libraries/DHTLib/dht.cpp: In member function 'int dht::_readSensor(uint8_t, uint8_t)':
/home/netpipe/.arduino15/packages/esp8266/hardware/esp8266/2.7.4/cores/esp8266/Arduino.h:215:118: error: cannot convert 'volatile uint32_t* {aka volatile unsigned int*}' to 'volatile uint8_t* {aka volatile unsigned char*}' in initialization
 #define portInputRegister(port)     (((port)==_PORT_GPIO16)?((volatile uint32_t*) &GP16I):((volatile uint32_t*) &GPI))
                                                                                                                      ^
/home/netpipe/Arduino/libraries/DHTLib/dht.cpp:116:29: note: in expansion of macro 'portInputRegister'
     volatile uint8_t *PIR = portInputRegister(port);
                             ^
exit status 1
Error compiling for board WeMos D1 R1.

**Comment by netpipe** [comment]
esp8266_peri.h seems to contain this but im unsure how to make it work

**Comment by RobTillaart** [comment]
Its rather late here so I will have a better look at it tomorrow if time
permits.

If I understand the question you want to use DHTlib on an ESP.

Have you tried DHTNew? As that has been used on ESP32 it might work better.
It is the successor of dhtlib...

To be continued

**Comment by NayanKaran** [comment]
Use,

https://github.com/xreef/PCF8574_library

It supports esp8266.

https://www.instructables.com/PCF8574-GPIO-Extender-With-Arduino-and-NodeMCU/

**Comment by netpipe** [comment]
DHTNew works but not with the pcf8574 so we need the original working :) someone said to use digitalRead to fix it ? , as for Nayan's comment https://github.com/skywodd/pcf8574_arduino_library/issues/14 i had this issue with that library unless that one is different..

**Comment by RobTillaart** [comment]
I have to release the automatic build of this library first before I dive into the issue.

**Comment by RobTillaart** [comment]
OK, done.

The error message
> /home/netpipe/Arduino/libraries/DHTLib/dht.cpp: In member function 'int dht::_readSensor(uint8_t, uint8_t)':
/home/netpipe/.arduino15/packages/esp8266/hardware/esp8266/2.7.4/cores/esp8266/Arduino.h:215:118: error: cannot convert 'volatile uint32_t* {aka volatile unsigned int*}' to 'volatile uint8_t* {aka volatile unsigned char*}' in initialization
#define portInputRegister(port) (((port)==_PORT_GPIO16)?((volatile uint32_t*) &GP16I):((volatile uint32_t*) &GPI))
^
/home/netpipe/Arduino/libraries/DHTLib/dht.cpp:116:29: note: in expansion of macro 'portInputRegister'
volatile uint8_t *PIR = portInputRegister(port);

These command are AVR specific commando's that are at the core of this library. 
That is the reason this library will **NEVER** work with ESP8266 or ESP32.

- As this library is replaced by the DHTNEW I will not rewrite it to make it ESP compatible.
- The DHTNEW library uses digitalRead() and digitalWrite() and works with ESP32 and should work with ESP8266.
  The core is essential identical, so that should make no difference.

**Comment by RobTillaart** [comment]
Can you describe what you want to achieve?

What I understand is "I want to read a DHT11 / 22 sensor by means of a PCF8574 chip instead of directly from the ESP8266"

Is that correct?

**Comment by RobTillaart** [comment]
Installed ESP8266 in my IDE and the DHTNEW library compiles just as expected.

**Comment by RobTillaart** [comment]
> Can you describe what you want to achieve?
> 
> What I understand is "I want to read a DHT11 / 22 sensor by means of a PCF8574 chip instead of directly from the ESP8266"
> 
> Is that correct?

A quick test with **my own PCF8574** library showed for an **UNO** the following timings.

|  I2C bus clock |  read time (us)  | write time (us) |
|:----|:----:|:----:|
| 100000 | 240 | 240 |
| 150000 | 176 | 176 |
| 200000 | 136 | 140 |
| 250000 | 116 |  80 |
| 300000 | 64 |  76 | 
| 350000 | 68 | 72 |
| 400000 | 56 | 72 |
| 450000 | 52 | 68 |

Above 450000 the chip did not respond properly. As the I2C clock is the same for any board, I can confidently assume that these numbers are in the same order of magnitude as the numbers one would get when using an ESP8266.

To be able to read to a DHT22 one need to be able to read as short pulses as ~28 us (see specs). What this test shows is that with an UNO,  it is time wise - as far as I measured - impossible to read a DHT22 indirectly through an PCF8574 by means of **polling**. 

Even with interrupts I expect it is impossible in terms of getting the timing right, but please prove me wrong.

**Comment by netpipe** [comment]
do you have example code for this using DHTnew ?   oh cool, i see you had to limit the read time due to I2C

**Comment by RobTillaart** [comment]
- https://github.com/RobTillaart/DHTNew
- https://github.com/RobTillaart/PCF8574

[PCF8574_performance.zip](https://github.com/RobTillaart/DHTlib/files/5869564/PCF8574_performance.zip)

**Comment by RobTillaart** [comment]
> "I want to read a DHT11 / 22 sensor by means of a PCF8574 chip instead of directly from the ESP8266" yes correct

As the timing of I2C does not allow this by polling, and as it is not possible with this DHTlib due to AVR specific code 
I close this issue.

If you have an interrupt PCF8574 version based upon DHTNew, you might reopen this issue under DHTNew repository.

**Comment by netpipe** [comment]
guess the part im having issues with is DHTNEW mySensor(16);   then   you cannot specify the PE. P1 P2 ports can you ?

**Comment by RobTillaart** [comment]
What do you mean by PE?

You can use a variable in the constructor, but then you cannot use the DHTNew object as global variable
see example - https://github.com/RobTillaart/DHTNew/blob/master/examples/dhtnew_runtime/dhtnew_runtime.ino

**Comment by netpipe** [comment]
DHTNEW sensor(PCF.read8());  is that valid ?

**Comment by RobTillaart** [comment]
The parameter for the constructor is a pin number.

So if the pcf.read8() return value indicates a pin number it is 100% valid. 

If the dht22 is connected to one of the pcf pins it is not. 

What do you want to achieve? 
Using multiple dht sensors with minimal pins?

**Comment by netpipe** [comment]
i dont think pcf.read8() does that.

basically esp8266 01s modules have 2 pins for i2c pin 0 and pin 2 so i've been designing code around that. with a pcf i can get 8 pins back adding other modules to.

I'll have a freelancer look at this its probably as simple as changing 32 bit to 16 bit

**Comment by RobTillaart** [comment]
The PCF8574 will give you 8 IO lines extra, the MCP23017 will even give you 16.

But all these chips that work over I2C are limited in the fastest pulse they can give and they can read. 
For I2C the speed is typically 100KHz or 400KHz or some do 1000 KHz.
That means that to read the 8 lines, at 1000 KHz you need to address the device and give the read command and read the 8 bits.
That will take (not measured) at least 25 us. So way too short to measure the pulses.
But again, surprise me with a working version.

### Solution
What you need is a **MAX14661**. That is a multiplexer chip that can be controlled by I2C to select a channel.
That way you can multiplex up to 16 DHT22 sensors on one single pin of the ESP8266 + 2 pins for the I2C of course.

- https://datasheets.maximintegrated.com/en/ds/MAX14661.pdf

**Comment by RobTillaart** [comment]
This in combination with a PCF8574 might be easier  (and cheaper)
- https://www.sparkfun.com/products/13906
