### ISSUE TITLE
v 1.32 less robust than v 1.08

### ISSUE THREAD

**Issue by wfdudley** [RobTillaart/DHTlib#6]
I've been using 1.08 for a long time now (since it was "current") and it is very robust, in the sense that if the DHT22 devices are on long wires, v 1.08 still is able to read the device.  I upgraded to DHTlib 1.32, and found that, while it could read a DHT22 on short leads (a few inches) it wouldn't read devices that were many feet away.  (Don't judge me, I have my reasons.)  I found that uncommenting line 185 in dht.cpp, which is:

`digitalWrite(pin, HIGH); // T-go`

fixes the problem.  This seems to me to be a "low cost" way of enhancing the reliability of reading DHT22's when the lead length is "sub optimal".  Please consider making this change to your code.

Thanks,
Bill Dudley

**Comment by RobTillaart** [comment]
HI Bill,

Thank you for this comment, I appreciate feedback from practice!
This HIGH is according to the datasheet but It is commented somewhere in history and I do not recall when/why.
looking at the 0.1.08 code I see that 

```cpp
	// REQUEST SAMPLE
	pinMode(pin, OUTPUT);
	digitalWrite(pin, LOW);
	delay(20);
	digitalWrite(pin, HIGH);
	delayMicroseconds(40);
	pinMode(pin, INPUT);
```

is replaced by  (0.1.32)

```cpp
    // REQUEST SAMPLE
    pinMode(pin, OUTPUT);
    digitalWrite(pin, LOW); // T-be
    if (wakeupDelay > 8) delay(wakeupDelay);
    else delayMicroseconds(wakeupDelay * 1000UL);
    // digitalWrite(pin, HIGH); // T-go
    pinMode(pin, INPUT);
````
So the ```delayMicroseconds(40);``` is gone too.  


As I moved my develop efforts to DHTNew library, can you give that lib a try? 
It does implement the ```digitalWrite(pin, HIGH); // T-go```

At least DHTNEW code indicates that the line should be there.
```cpp
  // HOST GIVES CONTROL TO SENSOR
  digitalWrite(_dataPin, HIGH);
  delayMicroseconds(2);
  pinMode(_dataPin, INPUT_PULLUP);
```
in fact by using the **INPUT_PULLUP** it does internally set the line to HIGH too

Can you verify if you use an **INPUT_PULLUP** in line 186, it works too?

**Comment by wfdudley** [comment]
I agree that the problem is likely rise time of the signal on that long wire, and just letting the wire "float" high works when the wire is short.  I tried the INPUT_PULLUP (without digitalWrite(pin, HIGH)) and that failed.  Using INPUT_PULLUP with the digitalWrite() still works, as one would expect.  So, for Q2, the answer is that the digitalWrite is necessary for long wire connections; the INPUT_PULLUP is insufficient.  Punchline: put back the digitalWrite().  (Oh, and the delaymicroseconds(40)
made no difference in my testing.)

As for Q1; I git cloned DHTNew, but the interface isn't just a drop-in.  I just want the stupidest possible use-case, and it wasn't at all obvious from your 13 examples which one that is.  Therefore, I declined to try to figure out what I need to change in my code to make it compatible with DHTNew.  It "looks like" that I could replace DHT.read22() with DHT.read(), DHT.temperature() with DHT.getTemperature(), (ditto Humidity), but I didn't look at the error conditions to see if they're different.  If the changes are as simple as that, perhaps I'll give it a go.

**Comment by RobTillaart** [comment]
Created a PR to include the T-GO signal. 
This makes the code logic more in sync with the DHTNew library. 
(did not investigate when/why it was removed)

**Comment by RobTillaart** [comment]
If there are other issues, please let me know!

**Comment by wfdudley** [comment]
I was feeling in a more generous mood this morning, and tried to use
dhtnew.  That
turned out to be a huge waste of time, because the new library is so
different from the
old one as to be almost unrecognizable from the application view.

I have THREE temp sensors, and before dhtnew, I could create ONE dht
object, and just call read22(pin)
to differentiate which sensor I wanted to read.  But in dhtnew, the pin is
specified in the constructor,
so I have to create three objects, and change my code around to call one of
the tree depending on
which sensor I want to read.  After changing a bunch of stuff to conform to
all the name changes
(temperature -> getTemperature, humidity -> getHumidity, etc) I realized
that specifying the pin in
the constructor was really going to require a re-write.

I think you should rename DHTNEW to DHT_COMPLETELY_INCOMPATIBLE.

Please don't stop supporting DHTlib.

Thanks for fixing the problem with DHTlib.

Bill Dudley

This email is free of malware because I run Linux.

**Comment by RobTillaart** [comment]
DHTlib will be supported for fixing bugs like this one, no worries. Just let me know.

DHTnew has too many users to rename it :) but its model / api is indeed different. 

Anyway, if there are other issues in dhtlib let me know.
